language: scala
sudo: required
dist: trusty
addons:
  apt:
    update: true

before_script:
  - git fetch --tags

jdk:
  - oraclejdk8

matrix:
  include:
    - stage: build
      env: CI_SCRIPT="mill __.__.test"
      jdk: oraclejdk8

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.4.0/0.4.0-11-26a18d && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - "$CI_SCRIPT"

